"""
Thread-safe in-memory ring buffers for dashboard data.

Two singletons are exported:
  event_store  — every filesystem event analysed by the monitor
  alert_store  — every alert generated by AlertGenerator

Both support:
  push(item)      — add an item (drops oldest when capacity is reached)
  all()           — list of all items (oldest first)
  since(n)        — last n items
  subscribe()     — generator that yields new items via SSE
"""

import queue
import threading
from collections import deque


class _RingBuffer:
    """Bounded deque with subscriber notification for SSE streaming."""

    def __init__(self, maxlen: int = 500):
        self._buf: deque = deque(maxlen=maxlen)
        self._lock = threading.Lock()
        self._subscribers: list[queue.SimpleQueue] = []
        self._sub_lock = threading.Lock()

    # ── write ─────────────────────────────────────────────────────────────

    def push(self, item: dict) -> None:
        with self._lock:
            self._buf.append(item)
        # Notify all live SSE subscribers.
        with self._sub_lock:
            dead = []
            for q in self._subscribers:
                try:
                    q.put_nowait(item)
                except Exception:
                    dead.append(q)
            for q in dead:
                self._subscribers.remove(q)

    # ── read ──────────────────────────────────────────────────────────────

    def all(self) -> list:
        with self._lock:
            return list(self._buf)

    def since(self, n: int) -> list:
        with self._lock:
            return list(self._buf)[-n:]

    def count(self) -> int:
        with self._lock:
            return len(self._buf)

    # ── SSE subscription ──────────────────────────────────────────────────

    def subscribe(self) -> queue.SimpleQueue:
        """Return a queue that will receive every future push."""
        q: queue.SimpleQueue = queue.SimpleQueue()
        with self._sub_lock:
            self._subscribers.append(q)
        return q

    def unsubscribe(self, q: queue.SimpleQueue) -> None:
        with self._sub_lock:
            try:
                self._subscribers.remove(q)
            except ValueError:
                pass


# ── module-level singletons ───────────────────────────────────────────────

event_store = _RingBuffer(maxlen=500)
alert_store = _RingBuffer(maxlen=200)
